//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlInventario {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idiomas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlInventario.Idiomas", typeof(Idiomas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string MensajeAdvertencia {
            get {
                return ResourceManager.GetString("MensajeAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de Activo Fijo {0} ya está asignado a otro artículo en el sistema..
        /// </summary>
        internal static string MensajeAdvertenciaActivoFijo {
            get {
                return ResourceManager.GetString("MensajeAdvertenciaActivoFijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artículo guardado correctamente..
        /// </summary>
        internal static string MensajeAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda de Empleado.
        /// </summary>
        internal static string MensajeBuscarEmpleado {
            get {
                return ResourceManager.GetString("MensajeBuscarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Automático].
        /// </summary>
        internal static string MensajeCodigoAutomatico {
            get {
                return ResourceManager.GetString("MensajeCodigoAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Duplicado.
        /// </summary>
        internal static string MensajeCodigoDuplicado {
            get {
                return ResourceManager.GetString("MensajeCodigoDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar el artículo: .
        /// </summary>
        internal static string MensajeErrorActualizarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorActualizarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el artículo: .
        /// </summary>
        internal static string MensajeErrorAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ningún empleado con el DNI ingresado. Por favor, verifique el número..
        /// </summary>
        internal static string MensajeErrorBuscarEmpleado {
            get {
                return ResourceManager.GetString("MensajeErrorBuscarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ninguna razón social con el RUC ingresado. Por favor, verifique el número..
        /// </summary>
        internal static string MensajeErrorBuscarRuc {
            get {
                return ResourceManager.GetString("MensajeErrorBuscarRuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo código no puede quedar vacío..
        /// </summary>
        internal static string MensajeErrorCodigoAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorCodigoAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar el comprobante: .
        /// </summary>
        internal static string MensajeErrorComprobante {
            get {
                return ResourceManager.GetString("MensajeErrorComprobante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una condición válida..
        /// </summary>
        internal static string MensajeErrorCondicionAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorCondicionAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una foto para el articulo..
        /// </summary>
        internal static string MensajeErrorDireccionAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorDireccionAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo DNI no puede quedar vacío..
        /// </summary>
        internal static string MensajeErrorDniAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorDniAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un estado válido..
        /// </summary>
        internal static string MensajeErrorEstadoAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorEstadoAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de baja no puede ser menor a la fecha de adquisición..
        /// </summary>
        internal static string MensajeErrorFechaBajaAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorFechaBajaAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha del fin de garantía no puede ser menor a la fecha de adquisición..
        /// </summary>
        internal static string MensajeErrorFechaGarantiaAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorFechaGarantiaAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una foto para el articulo..
        /// </summary>
        internal static string MensajeErrorFotoAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorFotoAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar la imagen: .
        /// </summary>
        internal static string MensajeErrorImagen {
            get {
                return ResourceManager.GetString("MensajeErrorImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una marca válida..
        /// </summary>
        internal static string MensajeErrorMarcaAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorMarcaAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo modelo no puede quedar vacío..
        /// </summary>
        internal static string MensajeErrorModeloAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorModeloAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo serie no puede quedar vacío..
        /// </summary>
        internal static string MensajeErrorSerieAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorSerieAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una ubicación válida..
        /// </summary>
        internal static string MensajeErrorUbicacionAgregarArticulo {
            get {
                return ResourceManager.GetString("MensajeErrorUbicacionAgregarArticulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        internal static string MensajeExito {
            get {
                return ResourceManager.GetString("MensajeExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Sin Categoría].
        /// </summary>
        internal static string MensajeSinCodigoAutomatico {
            get {
                return ResourceManager.GetString("MensajeSinCodigoAutomatico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECCIONE.
        /// </summary>
        internal static string OpcionSeleccione {
            get {
                return ResourceManager.GetString("OpcionSeleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de garantía o fecha de baja es anterior a la fecha actual. ¿Desea continuar?.
        /// </summary>
        internal static string VerificarFechasAgregarArticulo {
            get {
                return ResourceManager.GetString("VerificarFechasAgregarArticulo", resourceCulture);
            }
        }
    }
}
